{{- if .Values.sharding.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rust-hadoop.fullname" . }}-metaserver-shard2-pdb
  labels:
    {{- include "rust-hadoop.labels" . | nindent 4 }}
    component: metaserver-shard2
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "rust-hadoop.selectorLabels" . | nindent 6 }}
      component: metaserver-shard2
{{- end }}
